services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - app_network

# Volumes pour persistance de données
volumes:
  db_data:

# Réseaux pour la communication entre services
networks:
  app_network:
    driver: bridge
